// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hablzabjqwdusajkoevb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYmx6YWJqcXdkdXNhamtvZXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjkxOTYsImV4cCI6MjA2MzEwNTE5Nn0.Vt8DYuqfEu_7FHj8-xi_0CbNFfWqAUbyTTVzoY_yz0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);